T: None
N: None
M: None
d: 1  # num_modes
b: 8
type: "emg"
epochs: 500
lr: 0.0001
record: True
ev: False
m1_path: "data/none_data/kmeans_split/k3"
emg_path: "data/none_data/kmeans_split/k3"
behavioral_path: "data/none_data/kmeans_split/k3"
save_path: "checkpoints"
model: "decoder"
seed: 42
temperature: 1
weight_decay: 0.01
hidden_dim: 30
cluster_model_type: "method1"
decoder_model_type: ""
kmeans_cluster: 0
set_decoder_weights: False
label_type: "none"