T: None
N: None
M: None
d: 1  # num_modes
b: 8
type: "emg"
epochs: 500
lr: 0.0001
record: True
ev: False
m1_path: "data/set2_data/m1_set2_precision.npy"
emg_path: "data/set2_data/emg_set2_precision.npy"
behavioral_path: "data/set2_data/behavioral_set2_precision.npy"
save_path: "checkpoints"
model: "decoder"
seed: 42