T: None
N: None
M: None
d: 11  # num_modes
b: 512
type: "emg"
epochs: 500
lr: 0.01
record: True
ev: False
m1_path: ""
emg_path: ""
behavioral_path: ""
save_path: "checkpoints"
save_epochs: "none"
model: "combined"
seed: 42
temperature: 1.0
end_temperature: 0.01
anneal_temperature: "none"
weight_decay: 0.01
lambda_val: 0
l1_lambda_val: 0
overlap_lambda_val: 0
hidden_dim: 30
cluster_model_type: "method1"
decoder_model_type: ""
combined_model_type: "global_bias"
kmeans_cluster: 0
set_decoder_weights: "none"
label_type: "mouse"
remove_zeros: False
scale_outputs: False
mean_centering: "m1 and emg"
# eval_type: ""
eval_type: "val_60"
# eval_type: "test"
run_id: 962