T: None
N: None
M: None
d: 11  # num_modes
b: 64
type: "emg"
epochs: 500
lr: 0.01
record: True
ev: False
m1_path: ""
emg_path: ""
behavioral_path: ""
save_path: "checkpoints"
model: "combined"
seed: 43
temperature: 1
weight_decay: 0.01
hidden_dim: 30
cluster_model_type: "method1"
# decoder_model_type: "relu0.1"
# decoder_model_type: "relu0.01"
# decoder_model_type: "onlyrelu0.01"
# decoder_model_type: "onlytanh"
decoder_model_type: ""
kmeans_cluster: 0
set_decoder_weights: "none"
label_type: "mouse"
remove_zeros: False
scale_outputs: False
run_id: 378