T: None
N: None
M: None
d: 11  # num_modes
b: 512
type: "emg"
epochs: 500
lr: 0.01
record: True
ev: False
m1_path: ""
emg_path: ""
behavioral_path: ""
save_path: "checkpoints"
save_epochs: "none"
model: "combined"
seed: 42
temperature: 80.0
end_temperature: 1.5
# anneal_temperature: "cosine"
anneal_temperature: "sine"
weight_decay: 0.0025
hidden_dim: 30
cluster_model_type: "method1"
decoder_model_type: ""
kmeans_cluster: 0
set_decoder_weights: "none"
label_type: "mouse"
remove_zeros: False
scale_outputs: False
run_id: 521