T: None
N: None
M: None
d: 11  # num_modes
b: 64
type: "emg"
epochs: 500
lr: 0.01
record: True
ev: False
m1_path: ""
emg_path: ""
behavioral_path: ""
save_path: "checkpoints"
save_epochs: "none"
model: "combined"
seed: 42

temperature: 0.01

# temperature: 2.8
# temperature: 4.87
# temperature: 1.28
# temperature: 0.317

# temperature: 1.487
# temperature: 0.342
# temperature: 0.01

# temperature: 0.227
# temperature: 0.169

end_temperature: 0.01
anneal_temperature: "cosine"
weight_decay: 0.0025
hidden_dim: 30
cluster_model_type: "method1"
decoder_model_type: ""
kmeans_cluster: 0
set_decoder_weights: "none"
label_type: "mouse"
remove_zeros: False
scale_outputs: False
run_id: 442