T: None
N: None
M: None
d: 3  # num_modes
b: 8
type: "emg"
epochs: 500
lr: 0.001
record: True
ev: False
m1_path: "data/set2_data/m1_set2_t100.npy"
emg_path: "data/set2_data/emg_set2_t100.npy"
behavioral_path: "data/set2_data/behavioral_set2_t100.npy"
save_path: "checkpoints"
save_epochs: "none"
model: "combined"
seed: 42
temperature: 60.0
end_temperature: 1.5
# end_temperature: 0.01
# anneal_temperature: "cosine"
anneal_temperature: "sine"
weight_decay: 0.01
hidden_dim: 30
cluster_model_type: "method1"
# decoder_model_type: ""
decoder_model_type: "onlytanh"
# combined_model_type: "scalevector"
# combined_model_type: "scalevector_bias_init"
combined_model_type: "scalevector_bias"
kmeans_cluster: 0
set_decoder_weights: "none"
label_type: "set2"
remove_zeros: False
scale_outputs: False
run_id: 593